### ISSUE TITLE
Login delayed after upgrade to NC11

### ISSUE THREAD

**Issue by andyboeh** [nextcloud/user_saml#89]
After upgrading to Nextcloud 11.0.1 (from 10.0.x), using user_saml, all logins are delayed for a few seconds after submitting the login form. Then, everything seems to work fine. 

The Apache error log contains the following entries:
```PHP message: PHP Fatal error:  Uncaught Exception: Session has been closed - no further changes to the session are allowed in /var/www/cloud/lib/private/Session/Internal.php:154, referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
Stack trace:, referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
#0 /var/www/cloud/lib/private/Session/Internal.php(64): OC\\Session\\Internal->validateSession(), referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
#1 /var/www/cloud/lib/private/Session/CryptoSessionData.php(164): OC\\Session\\Internal->set('encrypted_sessi...', 'cc689c4d40ee69f...'), referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
#2 /var/www/cloud/lib/private/Session/CryptoSessionData.php(67): OC\\Session\\CryptoSessionData->close(), referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
#3 [internal function]: OC\\Session\\CryptoSessionData->__destruct(), referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
   thrown in /var/www/cloud/lib/private/Session/Internal.php on line 154, referer: https://censored.url/simplesaml/module.php/privacyidea/loginform.php?
```

The error message does not appear for the Sync Client (however, it's not using SAML but an app-specific password).

I tried to disable user_saml, the admin user (the only user in the internal user database) can login without delay and error message. We are not using any other user backend here.

Any ideas?

**Comment by andyboeh** [comment]
Hm, I checked a bit further, the error message and the load time do not seem to be related. I had a look at the browser's timing in the debugging console: Firefox seems to take significantly longer to load all the .js files from cache than Chromium.

The issue is not present on Chromium. I'm closing this and add a reference to nextcloud/server/issues/1303 here, since the error message seems to be similar.
